### ISSUE TITLE
Django version requirement?

### ISSUE THREAD

**Issue by jonathanstegall** [opennorth/represent-boundaries#39]
When I install represent-boundaries without specifying a Django version, I'm on 2.2.0, which does not support `python manage.py syncdb --noinput`. What is the most recent version of Django that is compatible with this app?

**Comment by jpmckinney** [comment]
We're using 1.11.

**Comment by jonathanstegall** [comment]
Thanks. I did manage to get it running with 2.2.0. It's just a matter of using `python manage.py migrate` instead, and also in urls.py it appears to expect this instead:

```
from django.contrib import admin
from django.urls import path
from django.conf.urls import include, url

urlpatterns = [
    path('admin/', admin.site.urls),
    url('', include('boundaries.urls')),
]
```

It will start the app in any case, at that point. I may still have compatibility issues though, as `python manage.py loadshapefiles` results in a `TypeError: '<=' not supported between instances of 'int' and 'list'` error.

Do you think I ought to downgrade to 1.11 and see what happens? I'm hoping my shapefiles (used in a much older version of boundaryservice) are still compatible, but I'm not sure how to evaluate that.

**Comment by jpmckinney** [comment]
The shapefiles shouldn't be a problem. Do you have the full stacktrace for the error?

**Comment by jpmckinney** [comment]
I've made the two changes to the installation instructions that you noted.

**Comment by jonathanstegall** [comment]
I think I figured out the rest. Our old version used something like `'namer': utils.simple_namer(['district'], normalizer=lambda x: x.lstrip('0')),` for the name function, and I was missing that I should instead be using `name_func=boundaries.clean_attr('district'),`. At least I think that is what I should be using. In any case, no more errors. I think I'm good on this!

Thanks for the willingness to help!
