### ISSUE TITLE
Removing a shapefile

### ISSUE THREAD

**Issue by jonathanstegall** [opennorth/represent-boundaries#41]
It seems like running `python manage.py loadshapefiles --reload` does not delete shapefiles that have previously been loaded. It does of course add new ones. I noticed that data/shapefiles has a remove_set.py file but it doesn't run successfully either.

Not sure if this is intentional/still needs to be built out, but wanted to point it out in case.

**Comment by jpmckinney** [comment]
Where is `remove_set.py`?

You can delete the shapefiles via the Django admin.

**Comment by jonathanstegall** [comment]
Sorry, my mistake on that file. It's from an older fork I had brought over without remembering.

Do you have any documentation about using the Django admin for this purpose?

**Comment by jonathanstegall** [comment]
Nevermind, I figured it out. Thanks much, I didn't realize previously that there was admin functionality. It's great to see!

**Comment by jpmckinney** [comment]
No worries :)
