### ISSUE TITLE
represent.opennorth.ca can't be reached

### ISSUE THREAD

**Issue by KarinG** [opennorth/represent-boundaries#43]
Hi @jpmckinney - I hope all is well! 

It appears the service has been down (looking at client logs) today. I sent an email to peck@ and to represent@ but if there are DNS issues those may not work either. So I thought I'd try to ping you on GitHub.

**Comment by jpmckinney** [comment]
Hi @KarinG, Peck is looking into it, but I have no estimate. I don't control DNS, and I'm no longer involved in maintaining the service.

That said, if you override your DNS to make represent.opennorth.ca resolve to 158.69.246.228, you should be able to access the service.

**Comment by KarinG** [comment]
👍 Thank you @jpmckinney
